### ISSUE TITLE
Next major version (3)

### ISSUE THREAD

**Issue by Kocal** [Yproximite/yProx-CLI#139]
### Features

- [x] Configure the tool through the `package.json` under the key `"yprox-cli"` (#144)
- [x] Add `API#isProduction()` method, it should check for `process.env.NODE_ENV === 'production'` (#145)
- [x] Add `rollup-plugin-graphql` for importing `.graphql` files as ES5 modules (#147)

### Refactoring

- [x] Rewrite the tool in TypeScript (#138, #150)
- [x] For the config, tools like `autoprefixer`, `cssnano` or `optipng` should not be under the key `handlers`. Rollup, sass or css are handlers, but those tools are not. We should do the same as bublé I think (#148)
- [ ] More and small functions, lighten command and handlers from utils methods 

### Removals

- [x] webpack handler, I think this was a huge mistake to add it. Yprox-CLI should stay light and simple, we already have Rollup which does the same thing. If you want to use webpack, then use it or use vue-cli/webpack-encore. (#140)
- [x] Remove `rollup-plugin-string` (#147)

### Misc/Internals

- [x] Create an `UPGRADE-3.0.md` file
- [x] Check if we can configure browserlist (autoprefixer) from `package.json` and/or `.browserslistrc` (yes, checked manually)
- [x] See for writing tests (unit and integration, but it would be nice to remove `test-app` folder) (#152)
- [x] ~Remove the default value `{}` of `path` options, in fact it should not be in the options schema~
- [x] If entry's `src` is not an array, then convert it to an array	(#143)
- [x] Replace `gulp-uglify-es` by `gulp-terser` (#146)
- [x] Named entries `{ handler: '..', src: ['...'], name: '<name>' }`, use the entry's name instead of printing all sources (when bundling) (#149)
